// Content for "Peptides Simplified". Edit here, then run: node scripts/build-learn.mjs
// Plain-English, no dosing. Evidence tags: 'human' = studies in people, 'animal' = animals, 'lab' = cells/test tubes.

export const SITE_NAME = 'Sequence';
export const UPDATED = '2026-09-26';

export const TIERS = {
  rx: { label: 'Approved Rx', blurb: 'An FDA-approved prescription medicine, backed by large human trials.' },
  human: { label: 'Human studies', blurb: 'Tested in people, but in small or limited studies.' },
  early: { label: 'Early research', blurb: 'Mostly animal or lab studies. Very little data in people.' },
};

export const TAGS = {
  weight: 'Weight loss',
  muscle: 'Muscle & recovery',
  healing: 'Healing & injury',
  skin: 'Skin & hair',
  sleep: 'Sleep',
  brain: 'Focus & mood',
  longevity: 'Aging & longevity',
  libido: 'Libido',
  immune: 'Immune & gut',
};

export const PEPTIDES = [
  {
    slug: 'semaglutide', name: 'Semaglutide', aka: 'Ozempic, Wegovy, Rybelsus', tier: 'rx', status: 'FDA-approved prescription',
    tags: ['weight', 'longevity'], seq: 'HAEGTFTSDVSSYLEGQAAKEFIAWLVRGRG', len: '31 amino acids', routes: 'Weekly injection or daily tablet',
    short: 'A lab-made copy of a gut hormone called GLP-1 that tells your brain you are full. It is the active ingredient in Ozempic and Wegovy.',
    what: 'After you eat, your gut releases a hormone called GLP-1. It tells your brain you have had enough and slows how fast your stomach empties. Semaglutide acts like GLP-1 but lasts about a week instead of a few minutes.',
    studies: [
      ['human', 'In a large 68-week trial, adults with obesity lost about 15% of their body weight on average, compared with about 2% on placebo.'],
      ['human', 'In a trial of 17,000+ people with heart disease and excess weight, it lowered the risk of heart attack, stroke and heart-related death by about 20%.'],
      ['human', 'It lowers blood sugar in type 2 diabetes, which is what it was first approved for.'],
    ],
    unknown: ['Most people regain much of the weight after stopping.', 'Very long-term effects past a decade are still being studied.'],
    cautions: ['Nausea, vomiting, diarrhea and constipation are common, especially early on.', 'Rare risks include pancreatitis and gallbladder problems.', 'Not for people with a personal or family history of medullary thyroid cancer or MEN2.'],
    legal: 'FDA-approved. Available only with a prescription.',
    related: ['tirzepatide', 'retatrutide', 'tesamorelin'],
  },
  {
    slug: 'tirzepatide', name: 'Tirzepatide', aka: 'Mounjaro, Zepbound', tier: 'rx', status: 'FDA-approved prescription',
    tags: ['weight'], seq: ['Y', 'Aib', 'E', 'G', 'T', 'F', 'T', 'S', 'D', 'Y', 'S', 'I', 'Aib', 'L', 'D', 'K', 'I', 'A', 'Q', 'K', 'A', 'F', 'V', 'Q', 'W', 'L', 'I', 'A', 'G', 'G', 'P', 'S', 'S', 'G', 'A', 'P', 'P', 'P', 'S'], len: '39 amino acids', routes: 'Weekly injection',
    short: 'A weight-loss medicine that copies two fullness hormones at once, GLP-1 and GIP. People sometimes call it a "GLP-2", but that name really belongs to a different gut hormone.',
    what: 'Tirzepatide switches on two hormone signals your body already uses after meals: GLP-1 and GIP. Hitting both at once seems to curb appetite more strongly than GLP-1 alone.',
    studies: [
      ['human', 'In a 72-week trial, adults with obesity on the highest dose lost about 21% of their body weight on average.'],
      ['human', 'In a head-to-head trial against semaglutide, people lost about 20% of their weight on tirzepatide versus about 14% on semaglutide.'],
      ['human', 'It is also approved to treat obstructive sleep apnea in adults with obesity.'],
    ],
    unknown: ['How well weight stays off after stopping.', 'Whether it protects the heart as strongly as semaglutide has shown. Those trials are still reporting.'],
    cautions: ['Stomach side effects like nausea and diarrhea are common.', 'Same thyroid cancer warning as semaglutide.', 'Can make birth control pills less reliable for a while after starting or raising the dose.'],
    legal: 'FDA-approved. Available only with a prescription.',
    related: ['semaglutide', 'retatrutide', 'mots-c'],
  },
  {
    slug: 'retatrutide', name: 'Retatrutide', aka: '"GLP-3", triple agonist', tier: 'human', status: 'Investigational, not approved',
    tags: ['weight'], seq: null, len: '39 amino acids', routes: 'Weekly injection (in trials)',
    short: 'An experimental weight-loss drug that copies three hormones at once. It has produced the largest weight loss seen so far in trials, but it is not approved yet.',
    what: 'Retatrutide acts on three hormone signals: GLP-1, GIP and glucagon. The glucagon part may help the body burn more energy, on top of eating less.',
    studies: [
      ['human', 'In its first large Phase 3 trial, people on the top dose lost around 28 to 30% of their body weight on average.'],
      ['human', 'It also eased knee osteoarthritis pain in people with obesity in that trial.'],
    ],
    unknown: ['Long-term safety, since it is still in trials.', 'When, or whether, the FDA will approve it.'],
    cautions: ['Stomach side effects similar to other GLP-1 drugs.', 'Products sold online as "research retatrutide" are not the tested drug and have no quality control.'],
    legal: 'Not FDA-approved. Only legally available inside clinical trials.',
    related: ['tirzepatide', 'semaglutide'],
  },
  {
    slug: 'tesamorelin', name: 'Tesamorelin', aka: 'Egrifta', tier: 'rx', status: 'FDA-approved for one use',
    tags: ['weight', 'muscle'], seq: 'YADAIFTNSYRKVLGQLSARKLLQDIMSRQQGESNQERGARARL', len: '44 amino acids', routes: 'Daily injection',
    short: 'A prescription peptide that tells your body to make more of its own growth hormone. It is approved to shrink deep belly fat in one specific group of patients.',
    what: 'Your brain releases a signal called GHRH that tells the pituitary gland to make growth hormone. Tesamorelin is a longer-lasting copy of that signal.',
    studies: [
      ['human', 'In people with HIV-related belly fat, it cut deep (visceral) belly fat by about 15% over six months.'],
      ['human', 'Early studies suggest it may reduce liver fat.'],
    ],
    unknown: ['How well it works for general fat loss in healthy people.', 'Belly fat tends to come back after stopping.'],
    cautions: ['Joint pain, swelling and injection-site reactions.', 'Can raise blood sugar.'],
    legal: 'FDA-approved for HIV-related abdominal fat. Other uses are off-label.',
    related: ['cjc-1295', 'sermorelin', 'ipamorelin'],
  },
  {
    slug: 'cjc-1295', name: 'CJC-1295', aka: 'Modified GRF(1-29), often paired with ipamorelin', tier: 'human', status: 'Compounded only, not approved',
    tags: ['muscle', 'sleep', 'longevity'], seq: 'YADAIFTQSYRKVLAQLSARKLLQDILSR', len: '29 amino acids', routes: 'Injection',
    short: 'A lab-made signal that nudges your body to release more growth hormone for days at a time.',
    what: 'CJC-1295 is a modified version of the body’s growth-hormone-releasing signal (GHRH), built to last much longer in the blood.',
    studies: [
      ['human', 'In small studies of healthy adults, one injection raised growth hormone levels several times over and kept IGF-1 higher for about a week or more.'],
    ],
    unknown: ['Whether higher growth hormone from CJC-1295 builds muscle or improves health in real life.', 'Long-term safety. Its drug development was stopped years ago.'],
    cautions: ['Flushing, water retention and tingling are reported.', 'Higher growth hormone can raise blood sugar.', 'Banned in sport by WADA.'],
    legal: 'Not FDA-approved. In 2026, HHS announced plans to let licensed compounding pharmacies make it with a prescription.',
    related: ['ipamorelin', 'sermorelin', 'tesamorelin'],
  },
  {
    slug: 'ipamorelin', name: 'Ipamorelin', aka: 'GH secretagogue', tier: 'human', status: 'Compounded only, not approved',
    tags: ['muscle', 'sleep'], seq: ['Aib', 'H', 'Nal', 'F', 'K'], len: '5 amino acids', routes: 'Injection',
    short: 'A tiny peptide that copies the "hunger hormone" ghrelin to trigger a pulse of growth hormone.',
    what: 'Ipamorelin acts on the same switch as ghrelin, a gut hormone that also tells the pituitary to release growth hormone. It is known for being more selective than older peptides like it.',
    studies: [
      ['human', 'It reliably causes a short burst of growth hormone in people.'],
      ['human', 'A trial testing it to speed gut recovery after surgery did not beat placebo.'],
    ],
    unknown: ['Whether it improves muscle, fat or sleep in healthy adults. There are no solid trials on that.'],
    cautions: ['Headache, flushing and increased hunger are reported.', 'Banned in sport by WADA.'],
    legal: 'Not FDA-approved. Included in the 2026 HHS plan to allow compounding with a prescription.',
    related: ['cjc-1295', 'sermorelin', 'tesamorelin'],
  },
  {
    slug: 'sermorelin', name: 'Sermorelin', aka: 'GRF(1-29)', tier: 'human', status: 'Compounded, formerly approved',
    tags: ['muscle', 'sleep', 'longevity'], seq: 'YADAIFTNSYRKVLGQLSARKLLQDIMSR', len: '29 amino acids', routes: 'Injection',
    short: 'The first 29 building blocks of the body’s own growth-hormone signal. It was once an FDA-approved drug for children.',
    what: 'Sermorelin is the shortest piece of GHRH that still works. It tells the pituitary to release growth hormone in its natural pulses.',
    studies: [
      ['human', 'It was approved in the 1990s to test and treat growth hormone deficiency in children.'],
      ['human', 'Small studies in older adults showed higher growth hormone and IGF-1, with mixed effects on body composition.'],
    ],
    unknown: ['Whether it slows aging or builds meaningful muscle in healthy adults.'],
    cautions: ['Injection-site reactions, flushing and headache.'],
    legal: 'The brand-name drug was withdrawn for business reasons, not safety. Today it is made by compounding pharmacies with a prescription.',
    related: ['cjc-1295', 'ipamorelin', 'tesamorelin'],
  },
  {
    slug: 'bpc-157', name: 'BPC-157', aka: 'Body Protection Compound 157', tier: 'early', status: 'Research compound, under FDA review',
    tags: ['healing', 'muscle', 'immune'], seq: 'GEPPPGKPADDAGLV', len: '15 amino acids', routes: 'Injection or oral',
    short: 'The most talked-about "healing peptide". It helped injuries heal faster in rats, but it has barely been tested in people.',
    what: 'BPC-157 is a small piece of a protein found in stomach juice. Scientists think it helps tissue repair partly by growing new blood vessels and calming inflammation.',
    studies: [
      ['animal', 'In rats, it sped up healing of tendons, ligaments, muscles, bones and the gut lining.'],
      ['animal', 'It protected the stomach and intestines from damage in many animal studies.'],
      ['human', 'Only a few tiny human reports exist, such as a small group with knee pain. None are large controlled trials.'],
    ],
    unknown: ['Whether it works in people at all.', 'Long-term safety. Because it helps grow blood vessels, some experts worry it could feed tumors.'],
    cautions: ['Quality of online products varies a lot.', 'Banned in sport by WADA.'],
    legal: 'Not FDA-approved. In 2026, HHS announced plans to allow licensed compounding with a prescription, and an FDA advisory committee reviewed it in July 2026. Rules are still changing.',
    related: ['tb-500', 'kpv', 'ghk-cu'],
  },
  {
    slug: 'tb-500', name: 'TB-500', aka: 'Thymosin beta-4 fragment', tier: 'early', status: 'Research compound, under FDA review',
    tags: ['healing', 'muscle'], seq: 'LKKTETQ', len: '7 amino acids', routes: 'Injection',
    short: 'A lab-made piece of a natural repair protein. It is often paired with BPC-157 for injuries.',
    what: 'Thymosin beta-4 is a protein your cells use to move, build blood vessels and repair damage. TB-500 is a short active piece of it.',
    studies: [
      ['animal', 'It improved wound, muscle and heart repair in animal studies.'],
      ['human', 'The full thymosin beta-4 protein was tested as eye drops and wound gels in people, with modest results. TB-500 itself has not been tested in people.'],
    ],
    unknown: ['Whether the fragment works like the full protein.', 'Long-term safety.'],
    cautions: ['Banned in sport by WADA; horse-racing positives are common.', 'Online product quality varies.'],
    legal: 'Not FDA-approved. Included in the 2026 HHS compounding plan and reviewed by an FDA advisory committee in July 2026.',
    related: ['bpc-157', 'ghk-cu'],
  },
  {
    slug: 'ghk-cu', name: 'GHK-Cu', aka: 'Copper peptide', tier: 'human', status: 'Cosmetic ingredient',
    tags: ['skin', 'healing', 'longevity'], seq: ['G', 'H', 'K', 'Cu'], len: '3 amino acids + copper', routes: 'Cream or serum (also injected)',
    short: 'A tiny copper-carrying peptide found in your blood. In skin creams, it has real human data for firmer, smoother skin.',
    what: 'GHK grabs onto copper and helps deliver it to cells. Your levels drop as you age. In skin, it signals cells to make collagen and repair damage.',
    studies: [
      ['human', 'In small studies of face creams, it improved skin firmness, thickness and fine lines over about 12 weeks.'],
      ['lab', 'In lab studies, it switched on genes linked to repair and switched down genes linked to inflammation.'],
      ['animal', 'It sped up wound healing in animals.'],
    ],
    unknown: ['Whether injecting it does anything that creams do not.', 'How much it helps hair growth. The evidence is thin.'],
    cautions: ['Creams are generally well tolerated.', 'Injected versions are much less studied.'],
    legal: 'Legal as a cosmetic ingredient. Injectable forms are included in the 2026 HHS compounding plan.',
    related: ['collagen-peptides', 'bpc-157'],
  },
  {
    slug: 'collagen-peptides', name: 'Collagen peptides', aka: 'Hydrolyzed collagen', tier: 'human', status: 'Dietary supplement',
    tags: ['skin', 'healing'], seq: ['G', 'P', 'Hyp', 'G', 'P', 'Hyp', 'G', 'P', 'Hyp'], len: 'Short chains of mixed length', routes: 'Powder or capsules by mouth',
    short: 'The peptide most people already take. It is collagen broken into small pieces so it mixes into drinks.',
    what: 'Collagen is the main protein in skin, tendons and bone. Collagen peptides are made by chopping it into short chains. Your gut breaks them down further, and a few small pieces reach the blood.',
    studies: [
      ['human', 'Many trials found modest improvements in skin elasticity and hydration after 8 to 12 weeks.'],
      ['human', 'Some trials found less joint pain in athletes and people with osteoarthritis.'],
    ],
    unknown: ['How much of the benefit is from the collagen itself versus just eating more protein.', 'Many studies are funded by supplement makers.'],
    cautions: ['Generally very safe. Check the source if you have fish or other allergies.'],
    legal: 'Sold over the counter as a dietary supplement.',
    related: ['ghk-cu'],
  },
  {
    slug: 'semax', name: 'Semax', aka: 'ACTH(4-10) analog', tier: 'human', status: 'Research compound (Rx in Russia)',
    tags: ['brain'], seq: 'MEHFPGP', len: '7 amino acids', routes: 'Nasal spray',
    short: 'A nasal spray peptide from Russia used for focus and stroke recovery.',
    what: 'Semax is built from a piece of the stress hormone ACTH, changed so it no longer affects stress hormones but still acts on the brain.',
    studies: [
      ['human', 'It is prescribed in Russia for stroke recovery and certain brain conditions, based mostly on Russian clinical studies.'],
      ['animal', 'In animals, it raised BDNF, a protein that supports brain cell growth.'],
    ],
    unknown: ['There are almost no large Western trials.', 'Whether it improves focus in healthy people.'],
    cautions: ['Nasal irritation is the most common complaint.'],
    legal: 'Not FDA-approved. Included in the 2026 HHS compounding plan and reviewed by an FDA advisory committee in July 2026.',
    related: ['selank', 'dsip'],
  },
  {
    slug: 'selank', name: 'Selank', aka: 'Tuftsin analog', tier: 'human', status: 'Research compound (Rx in Russia)',
    tags: ['brain', 'sleep'], seq: 'TKPRPGP', len: '7 amino acids', routes: 'Nasal spray',
    short: 'A calming nasal spray peptide from Russia studied for anxiety without drowsiness.',
    what: 'Selank is based on tuftsin, a small immune peptide your body makes. It seems to affect calming brain chemicals like GABA.',
    studies: [
      ['human', 'Small Russian trials in people with anxiety reported less anxiety, similar to a common anti-anxiety drug but without sedation.'],
    ],
    unknown: ['Independent trials outside Russia are lacking.'],
    cautions: ['Generally reported as well tolerated. Nasal irritation is possible.'],
    legal: 'Not FDA-approved. Included in the 2026 HHS compounding plan.',
    related: ['semax', 'dsip'],
  },
  {
    slug: 'epitalon', name: 'Epitalon', aka: 'Epithalon, AEDG', tier: 'early', status: 'Research compound, under FDA review',
    tags: ['longevity', 'sleep'], seq: 'AEDG', len: '4 amino acids', routes: 'Injection',
    short: 'A four-building-block peptide famous in anti-aging circles for its effect on telomeres, the caps on your DNA.',
    what: 'Epitalon was designed in Russia based on an extract from the pineal gland, the part of the brain that makes melatonin.',
    studies: [
      ['lab', 'In human cells, it switched on telomerase, the enzyme that rebuilds telomeres.'],
      ['animal', 'Some mice and fruit flies lived longer in studies.'],
      ['human', 'Small studies in older adults, mostly from one research group, reported better melatonin rhythms.'],
    ],
    unknown: ['Almost all research comes from one group and has not been independently repeated.', 'Whether it extends life in people.'],
    cautions: ['Very little human safety data.'],
    legal: 'Not FDA-approved. Reviewed for insomnia by an FDA advisory committee in July 2026.',
    related: ['mots-c', 'dsip', 'ss-31'],
  },
  {
    slug: 'dsip', name: 'DSIP', aka: 'Delta sleep-inducing peptide, emideltide', tier: 'early', status: 'Research compound, under FDA review',
    tags: ['sleep'], seq: 'WAGGDASGE', len: '9 amino acids', routes: 'Injection',
    short: 'A peptide first found in sleeping rabbits in the 1970s and named for deep sleep.',
    what: 'Scientists found DSIP in the blood of rabbits during deep sleep. What it actually does in the body is still not fully understood.',
    studies: [
      ['human', 'Small older studies in people with insomnia had mixed results.'],
      ['human', 'It was also studied to ease opioid and alcohol withdrawal symptoms.'],
    ],
    unknown: ['How it works and whether it reliably improves sleep.'],
    cautions: ['Limited safety data.'],
    legal: 'Not FDA-approved. Reviewed by an FDA advisory committee in July 2026 for insomnia and withdrawal.',
    related: ['epitalon', 'selank'],
  },
  {
    slug: 'mots-c', name: 'MOTS-c', aka: 'Mitochondrial peptide', tier: 'early', status: 'Research compound, under FDA review',
    tags: ['weight', 'longevity', 'muscle'], seq: 'MRWQEIGYIFYPRKLR', len: '16 amino acids', routes: 'Injection',
    short: 'A peptide made by your mitochondria, the power plants in your cells, that acts a bit like exercise in a molecule.',
    what: 'Most of your DNA sits in the cell’s nucleus, but mitochondria have their own. MOTS-c is coded there and helps cells handle sugar and energy.',
    studies: [
      ['animal', 'In mice, it improved insulin sensitivity, prevented diet-related weight gain and boosted exercise capacity.'],
      ['human', 'People’s natural levels rise with exercise and fall with age. Direct trials in people are very early.'],
    ],
    unknown: ['Whether taking it does anything in people.'],
    cautions: ['Very little human safety data.'],
    legal: 'Not FDA-approved. Reviewed by an FDA advisory committee in July 2026 for obesity and osteoporosis.',
    related: ['ss-31', 'epitalon', 'semaglutide'],
  },
  {
    slug: 'ss-31', name: 'SS-31', aka: 'Elamipretide, Forzinity', tier: 'rx', status: 'FDA-approved for one rare disease',
    tags: ['longevity', 'muscle'], seq: ['R', 'Dmt', 'K', 'F'], len: '4 amino acids', routes: 'Daily injection',
    short: 'A mitochondria-protecting peptide that became the first approved treatment for a rare genetic disease in 2025.',
    what: 'SS-31 sticks to the inner wall of mitochondria and helps keep their energy machinery working.',
    studies: [
      ['human', 'It received accelerated FDA approval in 2025 for Barth syndrome, a rare inherited disease that weakens muscles and the heart.'],
      ['human', 'A larger trial in another mitochondrial disease missed its main goal.'],
    ],
    unknown: ['Whether it has any anti-aging benefit in healthy people.'],
    cautions: ['Injection-site reactions are common.'],
    legal: 'FDA-approved only for Barth syndrome.',
    related: ['mots-c', 'epitalon'],
  },
  {
    slug: 'pt-141', name: 'PT-141', aka: 'Bremelanotide, Vyleesi', tier: 'rx', status: 'FDA-approved for one use',
    tags: ['libido'], seq: ['Nle', 'D', 'H', 'F', 'R', 'W', 'K'], len: '7 amino acids (ring-shaped)', routes: 'Injection as needed',
    short: 'A prescription peptide for low sexual desire that works on the brain, not blood flow.',
    what: 'PT-141 acts on melanocortin receptors in the brain, which are involved in desire. That is different from drugs like Viagra, which work on blood flow.',
    studies: [
      ['human', 'In two large trials of premenopausal women with low desire, it modestly improved desire and reduced distress compared with placebo.'],
    ],
    unknown: ['How well it works in men. Studies are small.'],
    cautions: ['Nausea is common, affecting about 4 in 10 people in trials.', 'It can briefly raise blood pressure.', 'Repeated use can darken patches of skin.'],
    legal: 'FDA-approved for premenopausal women with low sexual desire. Other uses are off-label.',
    related: ['kisspeptin'],
  },
  {
    slug: 'kisspeptin', name: 'Kisspeptin', aka: 'Kisspeptin-10', tier: 'human', status: 'Research compound',
    tags: ['libido'], seq: 'YNWNSFGLRF', len: '10 amino acids (short form)', routes: 'Injection or infusion (in studies)',
    short: 'The master switch for reproductive hormones, now being studied for fertility and desire.',
    what: 'Kisspeptin sits at the top of the hormone chain that controls testosterone, estrogen and fertility.',
    studies: [
      ['human', 'In people, it raises reproductive hormones and has been used to help trigger egg release in IVF studies.'],
      ['human', 'Brain-scan studies found it boosted brain activity linked to attraction and desire.'],
    ],
    unknown: ['Whether it works as a real-world treatment for low libido.'],
    cautions: ['Mostly short hospital studies so far.'],
    legal: 'Not FDA-approved.',
    related: ['pt-141'],
  },
  {
    slug: 'thymosin-alpha-1', name: 'Thymosin alpha-1', aka: 'Tα1, Zadaxin', tier: 'human', status: 'Approved abroad, not in the US',
    tags: ['immune'], seq: 'SDAAVDTSSEITTKDLKEKKEVVEEAEN', len: '28 amino acids', routes: 'Injection',
    short: 'An immune-boosting peptide from the thymus gland, approved in dozens of countries but not the US.',
    what: 'The thymus is where some immune cells learn their job. Thymosin alpha-1 helps those T cells mature and respond.',
    studies: [
      ['human', 'It is approved in many countries to support treatment of hepatitis B and C.'],
      ['human', 'It has been studied alongside vaccines and in serious infections, with mixed results.'],
    ],
    unknown: ['Whether it helps healthy people with "immune support".'],
    cautions: ['Generally well tolerated in trials.'],
    legal: 'Not FDA-approved. Included in the 2026 HHS compounding plan.',
    related: ['kpv', 'bpc-157'],
  },
  {
    slug: 'kpv', name: 'KPV', aka: 'Alpha-MSH fragment', tier: 'early', status: 'Research compound, under FDA review',
    tags: ['immune', 'healing', 'skin'], seq: 'KPV', len: '3 amino acids', routes: 'Oral, topical or injection',
    short: 'A three-building-block peptide studied for calming gut and skin inflammation.',
    what: 'KPV is the tail end of alpha-MSH, a natural hormone that helps control inflammation.',
    studies: [
      ['animal', 'In mice with colitis, it reduced gut inflammation.'],
      ['lab', 'In cell studies, it lowered inflammatory signals.'],
    ],
    unknown: ['There are no real human trials yet.'],
    cautions: ['Unknown in people.'],
    legal: 'Not FDA-approved. Reviewed by an FDA advisory committee in July 2026 for wound healing and inflammation.',
    related: ['bpc-157', 'thymosin-alpha-1'],
  },
  {
    slug: 'aod-9604', name: 'AOD-9604', aka: 'HGH fragment 176-191', tier: 'human', status: 'Research compound',
    tags: ['weight'], seq: 'YLRIVQCRSVEGSCGF', len: '16 amino acids', routes: 'Injection',
    short: 'A piece of growth hormone once developed as a fat-loss drug. In people, it did not beat placebo.',
    what: 'Scientists cut out the part of growth hormone thought to break down fat, hoping to get fat loss without the other effects of growth hormone.',
    studies: [
      ['animal', 'It reduced fat in obese mice.'],
      ['human', 'In trials with several hundred people, it did not cause meaningfully more weight loss than placebo, and development was stopped.'],
    ],
    unknown: ['Why the animal results did not carry over to people.'],
    cautions: ['Appeared well tolerated in trials.'],
    legal: 'Not FDA-approved. Included in the 2026 HHS compounding plan.',
    related: ['semaglutide', 'tesamorelin'],
  },
];
